# project tittle 
# student course, enrolment managment system 
# business problem : in a training institute the data is in excel file, as the number of students increasing mannualy analzysing/tracking the data is difficult*/
/*objective:
we need a system tracks the student details , courses , enrollment , instructors which is easy to track the details*/

CREATE database SQLPROJECT;
USE SQLPROJECT;
CREATE TABLE students(student_id INT primary key,
studentName varchar(20),
Gender varchar(20),
Age int,
City varchar(20),
Email varchar(20),
phone varchar(20),
JoiningDate date);
select * from students;

CREATE TABLE instructors(instructorID int primary key,
instructorName varchar(20),
Department varchar(20),
experience int);
select * from instructors;

CREATE table Courses(CourseID int primary key,
CourseName varchar(20),
DurationMonth int,
Fee decimal(10,2),
instructorID int,
foreign key (instructorID)
references instructors(instructorID));
select * from courses ;

CREATE TABLE enrollment (
    EnrollmentID int primary key,
    StudentsID int,
    CourseID int,
    EnrollmentDate Date,
    completionstatus varchar(20),
    Marks int,
    foreign key (StudentsID) references students(student_id),
    foreign key (CourseID) references Courses(CourseID)
);
select * from enrollment;


# business Analyzing questions
#total number of students
 
 select count(*) as total_students
 from students;
 
 #insights:
 # there are total 100 students in the institute
 
 #total number of courses
select count(*) as total_courses
from courses;
#insights:
# there are total 5 courses in the institute

#total number of instructors 
select count(*) total_instructors
from instructors;

#insights:
#there are total 5 instructors

#course with fee greater than 5000
select count(*) from courses
where Fee>5000;
# for python,power BI ,and data analytics courses fee is more than 5000

#students enrolled in each courses

select 
c.courseName,
count(e.EnrollmentID) as total_students
from courses as c
join enrollment e
on c.courseid = e.courseid
group by c.coursename;
 # most of the students are enrolled in data analytics 
 
 # Q list the students with their courses
 select s.studentname,
 c.coursename
 from students s
 join enrollment e
 join courses c
 on e. courseid = c.courseid;

# Q students who completed their course
select s.studentname,
c.coursename,
e.completionstatus
from students s
join enrollment e
on s.student_id = e.studentsID
join courses c
on c.courseid = e.courseid
where e.completionstatus = "completed"

# Q students who are still studying
select s.studentName,
c.coursename,
e.completionstatus
from students s.
join enrollment e
on s.student_id = e.studentsID
join courses c
on c.courseid = e.courseid
where e.completiomstatus = "ongoing";

# city wise students count 

select city,count(*) as total_students
from students
group by city;

# insights:
# using SQL query i have analyzed that most of the students are from hyderabad 

#Q revenue generated by each course
select c.coursename,
count(e.studentsID) * c. fee as revenue
from enrollment e
join courses c
on e.courseid = c.courseid
group by c.coursename, c.fee;

# insights"
# highest revenue is generated from data analytics 
# and least revenue is generated from the course exist